version: "3.9"
services:
  django:
    container_name: django
    build: ./
    environment:
      - DJANGO_SUPERUSER_PASSWORD=123
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: bash -c "python /usr/src/django/manage.py makemigrations && python /usr/src/django/manage.py migrate --noinput && python /usr/src/django/manage.py runserver 0.0.0.0:8000 && pip install -r /usr/src/django/requirements.txt"
    restart: always
    volumes:
      - ./:/usr/src/django
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis


  postgres:
    container_name: postgres
    image: postgres:15.2-alpine
    #    ports:
    #      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1771
      - POSTGRES_DB=cartographers
    restart: always
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7.0-alpine

