# Generated by Django 4.1.7 on 2023-05-02 10:42

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), choices=[(1, 'Filled'), (0, 'Blank')], size=2)),
                ('gives_coin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MonsterCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_order', models.CharField(choices=[('clockwise', 'Clockwise'), ('counterclockwise', 'Counterclockwise')], max_length=20)),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.shape')),
            ],
        ),
        migrations.CreateModel(
            name='DiscoveryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='discovery_cards/')),
                ('card_type', models.CharField(choices=[('mountain', 'Mountain')], max_length=20)),
                ('terrain', models.CharField(choices=[('water', 'Water'), ('field', 'Field'), ('forest', 'Forest'), ('village', 'Village')], max_length=20)),
                ('additional_terrain', models.CharField(blank=True, choices=[('water', 'Water'), ('field', 'Field'), ('forest', 'Forest'), ('village', 'Village')], max_length=20)),
                ('additional_shape', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_shape_cards', to='games.shape')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_shape_cards', to='games.shape')),
            ],
        ),
    ]
