# Generated by Django 4.1.7 on 2023-07-08 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectiveCardSQL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('lakefolk_map', 'Lakefolk Map'), ('gold_vein', 'Gold Vein'), ("enchanter's_dell", 'Enchanters Dell'), ('green_land', 'Green Land'), ('sentinel_wood', 'Sentinel Wood'), ('mountain_grove', 'Mountain Grove'), ('vast_plains', 'Vast Plains'), ('broken_roads', 'Broken Roads'), ('calderas', 'Calderas')], max_length=30)),
                ('text', models.TextField(blank=True, default=None, null=True)),
                ('image', models.ImageField(upload_to='objective_cards/')),
                ('category', models.CharField(choices=[('village', 'Village'), ('forest', 'Forest'), ('field_and_water', 'Field And Water'), ('formation', 'Formation')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonCardSQL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('points_to_end', models.IntegerField()),
                ('image', models.ImageField(upload_to='season_cards/')),
            ],
        ),
        migrations.CreateModel(
            name='ShapeSQL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_str', models.CharField(default='000000 000000 000000 000000 000000 000000', max_length=41)),
                ('gives_coin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TerrainCardSQL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20, null=True)),
                ('image', models.ImageField(upload_to='discovery_cards/')),
                ('card_type', models.CharField(choices=[('regular', 'Regular'), ('ruins', 'Ruins'), ('anomaly', 'Anomaly')], max_length=20)),
                ('terrain', models.CharField(blank=True, choices=[('water', 'Water'), ('field', 'Field'), ('forest', 'Forest'), ('village', 'Village')], max_length=20, null=True)),
                ('additional_terrain', models.CharField(blank=True, choices=[('water', 'Water'), ('field', 'Field'), ('forest', 'Forest'), ('village', 'Village')], max_length=20, null=True)),
                ('season_points', models.IntegerField(blank=True, null=True)),
                ('additional_shape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_shape_cards', to='games.shapesql')),
                ('shape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_shape_cards', to='games.shapesql')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterCardSQL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20, null=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='monster_cards/')),
                ('exchange_order', models.CharField(choices=[('clockwise', 'Clockwise'), ('counterclockwise', 'Counterclockwise')], max_length=20)),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.shapesql')),
            ],
        ),
    ]
