# Generated by Django 4.1.7 on 2023-05-02 11:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shape',
            name='shape',
        ),
        migrations.AddField(
            model_name='shape',
            name='shape_array2d',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(choices=[(1, 'Filled'), (0, 'Blank')]), size=2), default=None, null=True, size=2),
        ),
    ]
