# Generated by Django 4.1.7 on 2023-05-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_shape_shape_array2d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shape',
            name='shape_array2d',
        ),
        migrations.AddField(
            model_name='shape',
            name='shape_str',
            field=models.CharField(choices=[(1, 'Filled'), (0, 'Blank')], default='000000000000000000000000000000000000', max_length=41),
        ),
    ]
