# Generated by Django 4.1.7 on 2023-05-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_shape_shape_array2d_shape_shape_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shape',
            name='shape_str',
            field=models.CharField(default='000000000000000000000000000000000000', max_length=41),
        ),
    ]
