# Generated by Django 4.1.7 on 2023-05-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_shape_shape_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shape',
            name='shape_str',
            field=models.CharField(default='000000 000000 000000 000000 000000 000000', max_length=41),
        ),
    ]
