# Generated by Django 4.1.7 on 2023-05-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_shape_shape_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoverycard',
            name='name',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='monstercard',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='monster_cards/'),
        ),
        migrations.AddField(
            model_name='monstercard',
            name='name',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
