# Generated by Django 4.1.7 on 2023-05-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_discoverycard_name_monstercard_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoverycard',
            name='card_type',
            field=models.CharField(choices=[('mountain', 'Mountain'), ('regular', 'Regular')], max_length=20),
        ),
    ]
