# Generated by Django 4.1.7 on 2023-05-02 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_alter_discoverycard_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoverycard',
            name='additional_shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_shape_cards', to='games.shape'),
        ),
        migrations.AlterField(
            model_name='discoverycard',
            name='additional_terrain',
            field=models.CharField(blank=True, choices=[('water', 'Water'), ('field', 'Field'), ('forest', 'Forest'), ('village', 'Village')], max_length=20, null=True),
        ),
    ]
