# Generated by Django 4.1.7 on 2023-05-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_discoverycard_additional_shape_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectiveCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[("[('GREEN_LAND', 'green_land')]", 'My Choices')], max_length=30)),
                ('image', models.ImageField(upload_to='objective_cards/')),
            ],
        ),
    ]
