# Generated by Django 4.1.7 on 2023-05-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_objectivecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectivecard',
            name='name',
            field=models.CharField(choices=[('green_land', 'Green Land')], max_length=30),
        ),
    ]
