# Generated by Django 4.1.7 on 2023-05-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_seasoncard_discoverycard_season_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoverycard',
            name='card_type',
            field=models.CharField(choices=[('mountain', 'Mountain'), ('regular', 'Regular'), ('ruins', 'Ruins')], max_length=20),
        ),
    ]
