# Generated by Django 4.1.7 on 2023-05-09 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_alter_discoverycard_card_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonsterCard',
            new_name='MonsterCardSQL',
        ),
    ]
