# Generated by Django 4.1.7 on 2023-05-10 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_rename_monstercard_monstercardsql'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ObjectiveCard',
            new_name='ObjectiveCardSQL',
        ),
        migrations.RenameModel(
            old_name='SeasonCard',
            new_name='SeasonCardSQL',
        ),
    ]
