# Generated by Django 4.1.7 on 2023-05-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_rename_objectivecard_objectivecardsql_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiscoveryCard',
            new_name='DiscoveryCardSQL',
        ),
    ]
