# Generated by Django 4.1.7 on 2023-05-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_rename_shape_shapesql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoverycardsql',
            name='card_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('ruins', 'Ruins'), ('anomaly', 'Anomaly')], max_length=20),
        ),
    ]
