# Generated by Django 4.1.7 on 2023-06-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_alter_discoverycardsql_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoverycardsql',
            name='season_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objectivecardsql',
            name='name',
            field=models.CharField(choices=[('lakefolk_map', 'Lakefolk Map'), ('gold_vein', 'Gold Vein'), ("enchanter's_dell", 'Enchanters Dell'), ('green_land', 'Green Land'), ('sentinel_wood', 'Sentinel Wood'), ('mountain_grove', 'Mountain Grove'), ('vast_plains', 'Vast Plains'), ('broken_roads', 'Broken Roads'), ('calderas', 'Calderas')], max_length=30),
        ),
    ]
